### ISSUE TITLE
Unable to install Windows printer when cupd.conf is redirected to another folder

### ISSUE THREAD

**Issue by Olivier-11** [olbat/dockerfiles#100]
Hi,

In order to keep configuration after a pull of the container i add a volume mapping for config files

      volumes:
                  - "/var/run/dbus:/var/run/dbus"
                  - "/dev/bus/usb:/dev/bus/usb"
                  - "./config:/etc/cups"
With this config printer configuration is still there when the container is stopped and relaunch

But with this config i can not automaticaly install printer in Windows 10 it throw and error unable to connect
Everything work when /etc/cups is not map to external volume

It seems like ipp can't find drivers

Is there a way to have both config save to external volume and drivers installation automaticaly working ?

Best regards

**Comment by olbat** [comment]
Your question is related to the usage & configuration of Docker volumes on Windows. It doesn't really have anything to do with this repository. Please have a look at [the documentation](https://docs.docker.com/storage/) or reach out to the appropriate support channel.
