### ISSUE TITLE
Include Samba in CUPS for automatic printer discovery on Windows

### ISSUE THREAD

**Issue by Loizzus** [olbat/dockerfiles#101]
In the repo olbat/cupsd it would be nice to have Samba pre-installed and pre-setup so that it broadcasts all printers to Windows computers by default. 

Sorry if this is already happening, I couldn't figure out how.

**Comment by olbat** [comment]
Actually smbclient is already installed, see https://github.com/olbat/dockerfiles/blob/master/cupsd/Dockerfile#L21 .

However, I don't know how to install or configure it. If it requires another service then it should run using another container.

**Comment by Jacksaur** [comment]
Smbclient just allows CUPS access to SMB shared printers. "Samba" is the package that actually provides server functionality.

**Comment by olbat** [comment]
Samba is another daemon that should be launched separately from cupsd. Perhaps you could use another Docker image & container for that purpose & make it communicate with cupsd?

**Comment by Loizzus** [comment]
Why do you say it should be launched separately? At the end of the day the goal of a print server is to make managing printers effortless across all platforms. At the moment with it not being able to broadcast itself to windows devices it makes it mostly useless as in the business world the vast majority of end user devices are Windows machines. And almost nobody outside of businesses need a print server.

**Comment by olbat** [comment]
> Why do you say it should be launched separately?

Because that's how Docker has been designed to work: one system/service/function per container.

You can learn more about that [here](https://devops.stackexchange.com/questions/447/why-it-is-recommended-to-run-only-one-process-in-a-container) for example.

If you need Samba for your use-case, just create a Samba image, spin up a the service in a container and connect it to the cupsd one. Docker compose can help you to make that procedure less cumbersome.

**Comment by Loizzus** [comment]
Hey, while yes I completely agree with limiting the scope of a container to it's specific function (the Apache + MySQL example is a great example of what not to do) I don't think this applies to this situation. Making printers discoverable to Windows devices is a core function of CUPS and without it it isn't going to be useful to most people. Also having multiple instances of this container running with Samba in all of them will not have any negative consequences, it is still just as scalable. 

While yes it would probably be possible to write a compose file with shared volumes between the CUPS container and a dedicated samba container that is a very overcomplicated solution for something that should just be packaged together. 

But at the end of the day it is your project, I won't push you to add it any more. I also won't make a fork of the project as is yours is the most popular CUPS container and we really don't need yet another forked project. I was just hoping to make it slightly more useful.

**Comment by olbat** [comment]
I get your point. Yet, properly instantiating and keeping track of multiple services in a single container requires extra work and can degrade the stability of the main service. If for some reasons the samba service stops, the cups service will have to be stopped as well, which will have a negative impact for users that don't care at all about Samba.

If you want to implement your own Samba image & cups config please go for it. I can reference your config & work in the doc of this project to help others to get the same setup up & running. What I won't do is running another service that has nothing to do with cups in the same container.
