### ISSUE TITLE
Blanc pages after second install on host

### ISSUE THREAD

**Issue by JerrelS** [olbat/dockerfiles#106]
On the first try I
1. executed docker run -d -p 6031:631 -v /var/run/dbus:/var/run/dbus --name cupsd olbat/cupsd 
2. Configured my HP LaserJet Pro M203dw
3. Executed lpr -H <myhostip>:6031 -P <myprinternameincups> -o media=A5 <mypdffile>

Printouts were successfull many times

I removed the container docker container rm -f cupsd and executed steps 1-3 again.
This time the printer only prints blanc pages. with the text 
ERROR: syntaxerror
OFFENDING COMMAND: --nostringval--
or
some error
OFFENDING COMMAND
**** a font descr

Only halve of these errors or printed on the left border of the page

In an effort to resolve the issue, I removed the container, image, docker prune volume, docker prune container, reset the printer, updated printer firmware.

Still after running steps 1-3 the result is the same. Only blanc pages with error text.

Executed 1-3 on another host and all worked fine again, and the same issue appeared when reinstalling the container on that host.

Any idea what is happening here, and how to resolve it ?

regards

jerrel

**Comment by olbat** [comment]
I'm sorry, I just package cupsd in a Docker image. If you need support to configure your printer, please reach out to the appropriate support channels, see https://github.com/olbat/dockerfiles/tree/master/cupsd#troubleshooting .
