### ISSUE TITLE
[cupsd] avahi-daemon

### ISSUE THREAD

**Issue by HanaO00** [olbat/dockerfiles#109]
Hello, can you add avahi-daemon package and enable avahi-daemon.service for discovery when the printer is shared ?

Thanks

**Comment by olbat** [comment]
Hey @HanaO00 , if you need to have a separated service running for discovery, you can run it from another container (I'm pretty sure there are plenty images for avahi available online).

**Comment by olbat** [comment]
See these comments for more information on the topic: https://github.com/olbat/dockerfiles/issues/101#issuecomment-2015943810
