### ISSUE TITLE
HP1005 missing hp-plugin

### ISSUE THREAD

**Issue by wojciszpl** [olbat/dockerfiles#110]
Hi, it's not possible to properly configure this HP printer. For proper work it needs hp-plugin installed, but it can't be done from docker, as it doesn't has internet connection. Is it possible to fix it?

**Comment by olbat** [comment]
Hey @wojciszpl , is this plugin packaged for Debian and shared in the official repositories?

If yes, I can add it to the image, otherwise, please have a look at [this doc](https://github.com/olbat/dockerfiles/tree/master/cupsd#troubleshooting) 👍
