### ISSUE TITLE
cupsd: modify cupsd.conf

### ISSUE THREAD

**Issue by obbardc** [olbat/dockerfiles#14]
Is there any way to mount cupsd configs externally?

Are there any downsides to just mounting `/etc/cupsd` externally?

**Comment by olbat** [comment]
Are thinking about using a [volume](https://docs.docker.com/storage/volumes/#remove-volumes) for this?

I don't really understand, why would you want to modify cupsd.conf?

**Comment by obbardc** [comment]
Yeah, the volume is so the cupsd.conf files can be preserved between boots
and modified.
I want to allow other users on my network to add/remove printers as the
docker box is headless :)

**Comment by olbat** [comment]
Okay so if you just want to make a snapshot of the files from your image once you configured you can use [docker commit](https://docs.docker.com/engine/reference/commandline/commit/) to create a new image from the FS of the container then run a new container with it.

If you want your users to be able to add new printers at anytime, a volume will do but I still don't understand why you want to modify cupsd.conf ...

**Comment by olbat** [comment]
Can you tell me more about it?

**Comment by obbardc** [comment]
I want to use cups web interface from another PC than localhost so have to modify `cupsd.conf` to enable the different ACL.
I also want to update my docker instances by just pulling from your image and want the new image to use my external `cupsd.conf`.
For this to work seamlessly I think `/etc/cups` should be mounted using the `-v` docker option?

**Comment by olbat** [comment]
Yes in this case, volumes would do 👍

You may also need to [publish](https://docs.docker.com/config/containers/container-networking/) the port of the cupsd service and to make an initial [copy](https://docs.docker.com/engine/reference/commandline/cp/) of the configuration files contained in the image.

**Comment by olbat** [comment]
Is everything OK for you, can I close the issue?

**Comment by obbardc** [comment]
Yes all fine, but i was just mentioning it would be nice to extract the configuration files from the image for backups etc :-)

**Comment by olbat** [comment]
For this I think you can just run the container then copy the files somewhere using [docker cp](https://docs.docker.com/engine/reference/commandline/cp/), stop the container, modify the files then mount them [using a volume](https://stackoverflow.com/questions/42248198/how-to-mount-a-single-file-in-a-volume).

For this repository I prefer the keep the config files in the image since they may be changed in the Debian package and it would require someone to keep the track of the changes.

**Comment by olbat** [comment]
Bump! Though you might be interested by #15.
