### ISSUE TITLE
Web interface is not working

### ISSUE THREAD

**Issue by dropsonic** [olbat/dockerfiles#15]
Hi,

I've tried to run the container using the manual, but Web UI is not working at all.

If I use `--net=host`, CUPS error_log is empty, and I get this:
> 127.0.0.1 refused to connect. ERR_CONNECTION_REFUSED

I've also tried to run the container without `--net=host` (`631:631` port mapping).
In this case, CUPS error_log shows the following:
> Unable to open listen socket for address [v1.::1]:631 - Cannot assign requested address for address [v1.::1]:631 - Cannot assign requested address.

**netstat -plnt**

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      1/cupsd
```

And http://127.0.0.1:631/ shows me this:
> 127.0.0.1 didn’t send any data. ERR_EMPTY_RESPONSE

**Comment by dropsonic** [comment]
I've made it work by doing the following changes in the `cupsd.conf` file ([original article](http://www.alecburton.co.uk/docker/containers/cups/dockerfile/linux/blog/hp/git/docker-compose/print/printing/2017/11/05/printing-from-a-docker-container.html)):

1. Added `Add DefaultEncryption Never`
2. Changed `Listen localhost:631` to `0.0.0.0:631`
3. Added `Allow all` to `<Location />` and `<Location /admin>`

After that, Web UI started working.

**Comment by olbat** [comment]
Hello @dropsonic, I'd prefer to keep the default configuration files for the service (so they get updated with the packages).

I think that your issue is probably related to [Docker networking](https://docs.docker.com/network/#docker-ee-networking-features). What's OS is your host running?

I'll try to reproduce your issue ASAP (probably tomorrow).

**Comment by dropsonic** [comment]
Thank you, but there is no need to hurry, I've fixed it using `sed` to keep the configuration file up-to-date.
Many other `CUPS ` images also change that values.
Probably it's related to the fact that I'm running on Windows.

**Comment by dropsonic** [comment]
No problem, thanks for investigating.
I fixed it by adding the following lines to my Dockerfile:

```
RUN sed -i 's/Listen localhost:631/Listen 0.0.0.0:631/' /etc/cups/cupsd.conf
RUN sed -i 's/<Location \/>/<Location \/>\n  Allow All/' /etc/cups/cupsd.conf
RUN sed -i 's/<Location \/admin>/<Location \/admin>\n  Allow All/' /etc/cups/cupsd.conf
RUN echo 'DefaultEncryption Never' >> /etc/cups/cupsd.conf
```

**Comment by olbat** [comment]
Thanks for sharing!

Normally what I did does a ~equivalent modification to the config file (except for the `DefaultEncryption` setting) so the new image should fix your issue.

**Comment by dropsonic** [comment]
@olbat thank you!
