### ISSUE TITLE
user and passwort not good 

### ISSUE THREAD

**Issue by neudodo** [olbat/dockerfiles#18]
hello i try to use your images but the print/print user and password not good can you help me? 

My docker compose file 

version: '3'

services:
  cups:
    image: olbat/cupsd
    ports:
      - 631:631
    volumes:
      - /Users/neudodo/docker/cups/config:/var/run/dbus

**Comment by neudodo** [comment]
sorry i was a id..oot...

**Comment by olbat** [comment]
Hello @neudodo, what was the issue? Is there anything I can improve in the doc?
