### ISSUE TITLE
Unable to add printer using print as username and password

### ISSUE THREAD

**Issue by capndave** [olbat/dockerfiles#22]
Hi. I ran the docker container exactly according to your instructions and I can open the cups GUI at http://127.0.0.1. I'm trying to add a printer, and am being asked for a username and password. I entered print for both, but it doesn't work. Any tips?

Docker containers are hosted on an Ubuntu server, and I've tried to connect from both that server and from an external Mint client on our network.

**Comment by olbat** [comment]
I think that @neudodo had the same issue a few months ago (see #18) but I don't know what solved the issue... I'm going to investigate.

**Comment by olbat** [comment]
I gave a try to the latest image (e90018ee4c4c) and didn't have any issue with the user/password.
What problem do you have exactly, do you get an error?

**Comment by olbat** [comment]
I'm going to close the issue, please let me know if you still have a problem using the image.

**Comment by Laerolf** [comment]
Hello Olbat, some time went by again but I got this issue now that I couldn't use my own users from the host, I'm not sure how this can be done?

**Comment by Laerolf** [comment]
Yes but in the end I changed my mind, need to find some other solution for my issue.

I have several Docker containers and one of them is a Java Spring Boot application that needs to be able to add printers to a Cups instance. Thank you for your time!
