### ISSUE TITLE
Printing error: Unable to determine number of pages, page count: -1

### ISSUE THREAD

**Issue by charlescng** [olbat/dockerfiles#25]
I'm running olbat/cupsd: 7c36346746d6

Windows 10 Test page prints OK. I am seeing the following issue while printing from Chrome 78.0.3904.70 on MacOS Mojave 10.14.6:

> D [26/Oct/2019:14:51:24 -0400] [Job 7] Device protocol: 2
D [26/Oct/2019:14:51:24 -0400] [Job 7] Sending data to printer.
D [26/Oct/2019:14:51:24 -0400] [Job 7] Process is dying with \"Unable to determine number of pages, page count: -1
D [26/Oct/2019:14:51:24 -0400] [Job 7] \", exit stat 3
D [26/Oct/2019:14:51:24 -0400] [Job 7] Cleaning up...
D [26/Oct/2019:14:51:24 -0400] [Job 7] PID 190 (/usr/lib/cups/filter/foomatic-rip) stopped with status 3.
D [26/Oct/2019:14:51:24 -0400] [Job 7] Hint: Try setting the LogLevel to "debug" to find out more.
D [26/Oct/2019:14:51:24 -0400] [Job 7] Sent 0 bytes...
D [26/Oct/2019:14:51:24 -0400] [Job 7] Waiting for read thread to exit...
D [26/Oct/2019:14:51:24 -0400] [Job 7] PID 191 (/usr/lib/cups/backend/usb) exited with no errors.
D [26/Oct/2019:14:51:24 -0400] [Job 7] End of messages
D [26/Oct/2019:14:51:24 -0400] [Job 7] printer-state=3(idle)
D [26/Oct/2019:14:51:24 -0400] [Job 7] printer-state-message="Sending data to printer."
D [26/Oct/2019:14:51:24 -0400] [Job 7] printer-state-reasons=none

It looks like the following `cups-filters` bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926576

It claims that the bug was fixed in `cups-filters` 1.22.5-1

Here are the related apt packages:
```
# apt list cups-filters
Listing... Done
cups-filters/now 1.25.11-1 amd64 [installed,local]
# apt list ghostscript
Listing... Done
ghostscript/now 9.27~dfsg-3.1 amd64 [installed,local]
```
Since the image is using cups-filters 1.25.11-1, it _should_ contain the fix.

@olbat Have you encountered this yourself? Maybe the fix is not in the debian/testing image?

**Comment by olbat** [comment]
Hi @charlescng, no I did not encountered this issue. However I don't think I ever tried to print from macOS...

Maybe you can mention your setup and your issue on this bug report's page?

**Comment by charlescng** [comment]
I'll follow up on that `cups-filters` bug report.

Thanks.
