### ISSUE TITLE
/etc/cups Folder

### ISSUE THREAD

**Issue by CyrosX** [olbat/dockerfiles#26]
Dear olbat,
would it be possible to allow the mount/binding of the cups folder to a folder on the host
in a next version?
(With first copying over the standard cups files to this folder).
This would make it very easy to backup the (only) necessary files.
I've done that manually (I only needed printers.conf) and it worked very well!
...
Is there any secret by connecting a CUPS client to this docker?  (does the connecting
container need to be linked to the cups server?)

**Comment by olbat** [comment]
Hello @CyrosX,

I'm not 100% sure about that but I think that your first issue could be solved easily using [Docker volumes](https://docs.docker.com/storage/volumes/). In that case, no changes are needed in the Dockerfile, you'll just have to add some runtime arguments.

For the question about CUPS client and a server running using this Docker image, from what I recall, the daemon is listening to any available interface meaning that if your client can reach the daemon's container, you should be able to use the service.

If you are running the client within another Docker container, I think that having a look to [Docker networks' doc.](https://docs.docker.com/network/network-tutorial-standalone/) could be helpful.

**Comment by olbat** [comment]
Any news @CyrosX, can I close the issue?
