### ISSUE TITLE
Problem running cups on a QNAP NAS

### ISSUE THREAD

**Issue by redfirebrooks** [olbat/dockerfiles#27]
Hello,
I tied this 
docker run -d -p 631:631 -v /var/run/dbus:/var/run/dbus --name cupsd --net=host olbat/cupsd
with my QNAP was. The container starts, I can even access the config pages on port 631; but the container stops suddenly after 20-30 seconds.. 
I do not have a clue what to do to solve it.

**Comment by olbat** [comment]
Do you see any error message in the service's logs?

**Comment by redfirebrooks** [comment]
pretty poor logs indeed


Info | 2020/01/21 23:25:42 | System | admin | Logs export to ctstation_log.csv
-- | -- | -- | -- | --
Info | 2020/01/21 20:28:51 | Container | admin | Start container (docker, d0339421ba6f, cupsd)
Info | 2020/01/21 20:28:18 | Container | admin | Start container (docker, d0339421ba6f, cupsd)
Info | 2020/01/21 20:26:43 | Container | admin | Destroy container (docker, ec06943a9a98, cupsd)
Info | 2020/01/21 20:22:00 | Container | admin | Start container (docker, ec06943a9a98, cupsd)
Info | 2020/01/21 20:21:21 | Container | admin | Start container (docker, ec06943a9a98, cupsd)
Info | 2020/01/19 20:42:32 | Container | admin | Finished background task (create, nginx-1)

nothing really useful I guess

maybe I should create a new container and mapping the cups logs directory ?

**Comment by olbat** [comment]
I'm speaking about logs from the Docker container (see [docker logs](https://docs.docker.com/engine/reference/commandline/logs/)).

Yes, you can also use a volume to store the cups logs directory however I'm not 100% sure that cupsd will write any logs there, to be verified...

**Comment by redfirebrooks** [comment]
Hello 
no logs at all... I tried docker logs --follow cups but not a line

I rebooted the nas and now it seems to work with
docker run -d -p 6310:631 -v /var/run/dbus:/var/run/dbus --name cupsd olbat/cupsd

I set the 6310 port because it is already in use, I guess by the poor QNAP cups version.

But I can't access to the administration page, I have this message (sorry in french)

Mise à niveau obligatoire
Vous devez accéder à cette page par l’URL https://10.0.3.3:631/admin/.

**Comment by olbat** [comment]
Since you have no errors docker logs, can you also have a look to cupsd logfile: _/var/log/cups/error_log_ (you can do so using [docker exec](https://docs.docker.com/engine/reference/commandline/exec/)).

Your analysis seems to be point in the good direction. If another service is already using the port 631 the service from the container won't be able to use it too. Maybe you can try to disable this other service?

(Also if you expose the service to the port 6310, you should try to the admin interface on the same port...)

Anyway, this issue does not seems to be related to this docker image but more to your runtime environment, isn't it?

**Comment by redfirebrooks** [comment]
Yep... I do not understand how docker networks work on QNAP nas.

**Comment by olbat** [comment]
Did you have a look to the log files? Or access to the admin interface using the right port (6310)?

**Comment by redfirebrooks** [comment]
Hello
Did not find anything useful in the log



Q
Frédéric
Envoyé de mon iPhone

**Comment by olbat** [comment]
What about trying to open the admin page on the port 6310?

**Comment by olbat** [comment]
Closing the issue as it's open for a while with no new answers.

**Comment by redfirebrooks** [comment]
sorry I was busy this last weeks
actually i am accessing the cups container using the ip adress of my nas 192.168.1.20 and the port 6310.
The error message when I try to add a printer mention the ip address of the container network : https://10.0.3.3:631

**Comment by olbat** [comment]
Are you running with an up to date image? Can you share the error message?

**Comment by redfirebrooks** [comment]
Hello,
the error message is
> Mise à niveau obligatoire
> Vous devez accéder à cette page par l’URL https://10.0.3.3:631/admin/.

I have stopped the container and then I made a  `docker pull olbat/cupsd` to update the image and then restarted it. I am not sure it is the correct way to update it. I will prune everything and restart from  scratch with a docker-compose file.

**Comment by olbat** [comment]
It looks to me that the error is related to the usage of HTTP instead of HTTPS here.
Can you configure the interface to display English error messages?

**Comment by redfirebrooks** [comment]
Hi,
I have removed the previous container and tried to resinstall it with `docker run -d -p 6310:631 -v /var/run/dbus:/var/run/dbus --name cupsd olbat/cupsd` ...
unfortunately now the container seems to be in a start/stop loop again. 
I can't reboot my nas right now.
