### ISSUE TITLE
Error launching docker image

### ISSUE THREAD

**Issue by ferbulous** [olbat/dockerfiles#28]
Hi, I'm running the cups on my docker, but there's some error starting it up
on raspbian 4 buster.

`standard_init_linux.go:211: exec user process caused "exec format error"

standard_init_linux.go:211: exec user process caused "exec format error"

standard_init_linux.go:211: exec user process caused "exec format error"`

Please do let me know if I can provide other logs.

**Comment by olbat** [comment]
Could you provide me with the Docker command you typed to run the container?

It look more like an error related to the way you're running the container to me than something related to this specific Docker image.

If you're running a custom script, you might be interested by [this post](https://stackoverflow.com/questions/42494853/standard-init-linux-go178-exec-user-process-caused-exec-format-error).

**Comment by ferbulous** [comment]
I used the docker command as in front page

`docker run -d -p 631:631 -v /var/run/dbus:/var/run/dbus --name cupsd olbat/cupsd`

**Comment by olbat** [comment]
I just tested and it work fine on a Linux x86-64 system.

The problem looks related to your Docker runtime environment: the image has been built for x86-64 systems and your system is most probably running on ARM arch (it seems to be a common issue, cf. [this](https://github.com/pi-hole/docker-pi-hole/issues/519) and [that](https://blog.hypriot.com/getting-started-with-docker-on-your-arm-device/) for example).

I suggest you to rebuild the image from your ARM system changing the base image in the _FROM_ statement of the [Dockerfile](cupsd/Dockerfile) to a Debian image for ARM systems (e.g. [one of those](https://github.com/docker-library/official-images#architectures-other-than-amd64)).

**Comment by olbat** [comment]
The source of the problem was identified, I'm going to close the issue.

(I might add images for non x86-64 images someday but have no plan to do so in the near future)

**Comment by olbat** [comment]
Hey @Noschvie , no, mostly because the automated building system I'm using doesn't offer support for arm64.
