### ISSUE TITLE
docker won't start with volumes mapped

### ISSUE THREAD

**Issue by Mothy-Tim** [olbat/dockerfiles#29]
Hi, I have been trying to setup your cups docker on Unraid and can get it working but cannot work out how to make my setup persist a reboot! I've tried mapping /etc/cups to appdata/cups/config on host but this causes the container to fail to start, my limited knowledge of docker says that appdata is overwriting the container when I want it the other way round yes? Also need the HP plugin to persist as my Laserjet CP1025 color needs the propriatry plugin! If I run hp-plugin in the container console and accept the license then it works until reboot!

My docker run command:
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='cupsd' --net='host' -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'TCP_PORT_631'='631' -v '/var/run/dbus/':'/var/run/dbus/':'rw' -v '/dev/':'/dev/':'rw' -v '/mnt/user/appdata/cupsd/logs':'/var/log':'rw' -v '/mnt/user/appdata/cupsd/config':'/etc/cups/':'rw' -v '/mnt/user/appdata/cupsd/hpconfig':'/etc/hp/':'rw' 'olbat/cupsd' `

Yours hopefully,
Tim

**Comment by olbat** [comment]
Hello, your guess was right: that's not how you should use Docker volumes to persist your config files (here is [some documentation](https://docs.docker.com/storage/) that you might find useful).

For your configuration issue, one way to do it will be to use [docker cp](https://docs.docker.com/engine/reference/commandline/cp/) to copy the configuration files your interested in into your host's volume directory then start the container mounting this directory as a volume (you might need to change files ownership for it to work correctly).

For the HP plugin: I have no idea about how this thing is working, hope you'll be able to find some documentation on their website or on the web to figure out which files it depends on.

Good luck with your research.

**Comment by olbat** [comment]
I'm going to close the issue as it's not really related to this project but you can continue to comment if you need more help.

**Comment by Mothy-Tim** [comment]
Ok thanks, I’ll let you know how I get on!
Cheers 
Tim
