### ISSUE TITLE
Add support for iOS AirPrint service discovery via Avahi

### ISSUE THREAD

**Issue by goldserve** [olbat/dockerfiles#30]
This debian based cups is the latest and I can print my test page but it doesn't support AirPrint which is what I am looking for. Possible to add support?

**Comment by olbat** [comment]
I'm not sure that adding AirPrint support will be trivial (cf. [Debian wiki](https://wiki.debian.org/CUPSAirPrint)), it might also need to have access to OS features that are not accessible to Docker containers out of the box.

If you find a way to make it work that doesn't make the _Dockerfile_ overly complicated or make the generated image twice bigger, I'll be happy to review your MR and integrate your change to the base image.

**Comment by olbat** [comment]
I'll close this issue for now, please reference it if you create a merge request to implement this feature.
