### ISSUE TITLE
/config

### ISSUE THREAD

**Issue by forcefullpower** [olbat/dockerfiles#31]
Is there a way to create a /config so that when I create  printer and it auto update or I recreate it I don't loss all configuration data.

**Comment by olbat** [comment]
I think this is more a question about Docker than a question related to the _cupsd_ image (I guessed) generated using a _Dockerfile_ from repository.

I'm going to close the issue as it's not related to this repository.

This comment should help you to get over with your issue: https://github.com/olbat/dockerfiles/issues/14#issuecomment-447551685 .
