### ISSUE TITLE
Trying to log in with default print/print creds just puts me in a "Confirm Form Resubmission" loop.

### ISSUE THREAD

**Issue by spierepf** [olbat/dockerfiles#33]
I followed your instructions on https://hub.docker.com/r/olbat/cupsd but when I try to connect to configure a printer, all I get are alternating "Sign In" and "Confirm Form Resubmission" pages.

**Comment by olbat** [comment]
I guess this documentation is probably outdated. Can you try the instructions from the [README](https://github.com/olbat/dockerfiles/tree/master/cupsd) file of this repo?

**Comment by olbat** [comment]
No updates, I guess the problem is solved? If not please re-open the issue.
