### ISSUE TITLE
Remote access for cupsd

### ISSUE THREAD

**Issue by sean-abbott** [olbat/dockerfiles#34]
I'm running the cupsd image on a box I use as a "server" and accessing it from my desktop.

it tries to upgrade the connection to https when I connect remotely

https://forums.freebsd.org/threads/cups-remote-admin-fails.18924/

provided a solution for me. I can add it to the readme if you want? Or maybe there's a better solution, I don't know.

**Comment by olbat** [comment]
It looks to me like a nice addition to the base image. I'm going to change the default configuration to include this option.

Could you test the new image in your setup once the MR has been merged?
