### ISSUE TITLE
Is there an arm64 version of cupsd docker?

### ISSUE THREAD

**Issue by wyap-echo** [olbat/dockerfiles#37]
framework | ARMv8 Processor rev 4 (v8l) x 4
I have a raspberry pie-like piece of hardware and want to run cupsd images on it. Any chance of adaptation?

**Comment by olbat** [comment]
Hello @wyap-echo, there is no version of the cupsd Docker image for the ARM arch. I do not plan to add any in the near future but if you have access to a machine that has an ARM CPU, you should be able to easily build it yourself (see [this comment](https://github.com/olbat/dockerfiles/issues/28#issuecomment-605423719)).
