### ISSUE TITLE
No device can locate shared printers

### ISSUE THREAD

**Issue by hakarune** [olbat/dockerfiles#50]
after adding 3 printers and 2 classes to CUPs and changing servername in the config as directed, no device on the network can see shared printers. Even the server running the docker cannot see the printers.

**Comment by jmotiwala** [comment]
I am trying to use this image as well with our application.

My client application has ServerName 127.0.0.1:631 added to the client.conf file. But when I run lpstat -v I always get scheduler is not running.

How can I make my app connect to the cups print server so it can see the printer I have shared out.

**Comment by olbat** [comment]
Please reach out to a more appropriate channel to get support about CUPS setup, cf. [this comment](https://github.com/olbat/dockerfiles/issues/48#issuecomment-776858057).
