### ISSUE TITLE
Adding Brother Drivers

### ISSUE THREAD

**Issue by pcwii** [olbat/dockerfiles#51]
Any chance you could add the drivers for Brother Printers?
eg.
https://support.brother.com/g/b/downloadlist.aspx?c=ca&lang=en&prod=hll2320d_us_as&os=128

**Comment by olbat** [comment]
If they're distributed as Debian packages, on [the official package registry](https://www.debian.org/distrib/packages), no. Sorry about that but don't want to start adding every snowflake proprietary driver in the image, I'm not even sure that it would be ok from a legal standpoint as most of the time you also have to accept some EULA.

Can you check if they're available in the registry?
If they are, can you provide me with the package name(s)?
I'll be happy to add them in the image!

**Comment by olbat** [comment]
@pcwii ?

**Comment by pcwii** [comment]
@olbat sorry, have not had a chance to look into this. Not entirely sure what to look for. To confirm your request. All I am certain of is that there is a debian package on the Brother website, and yes it does require an EULA to download.

**Comment by olbat** [comment]
If there is an EULA to accept, it will not be possible to distribute them with the image (I cannot accept the EULA on behalf of the users of the image).

**Comment by olbat** [comment]
@pcwii, any news?

**Comment by olbat** [comment]
No news, closing the issue.
