### ISSUE TITLE
Synology NAS docker, CUPS not printing information sent via IPP

### ISSUE THREAD

**Issue by Paytah232** [olbat/dockerfiles#53]
Hi there,

I'm not sure exactly where to start with this one, or exactly what information to give, but I will be happy to supply logs etc if requested. Basically I am running this docker container on my Synology NAS, latest DSM 7.0 (was running on version 6 before as well with same issue), and the printer (Brother QL810W) seems to hang on jobs sent via IPP using nodeJS. It goes into a waiting to print mode that never ends. I know the printer does work correctly through CUPS, as I am able to print a test page via the CUPS interface as well as change the label stock etc. hHre is the process I go through:
- Generate PDF file using nodeJS on same server running CUPS
- Send PDF file via IPP to CUPS printer
- Printer receives and processes jobs, but hangs and never prints. 
 - The light flashes green, but no error pops up, it is simply waiting to print, as if it hasn't sent all the data.

I will compile a zip that has the code and output that I see and upload it shortly. For now, I have uploaded what I have access to, which is the nodeJS file that sends the data to cups.
[nodetest.zip](https://github.com/olbat/dockerfiles/files/6952512/nodetest.zip)

I hope you can help me work this one out. I feel like it is so close to working, but something small is missing. Thanks!

**Comment by olbat** [comment]
Hello @Paytah232,

Thank you for your detailed message. I'd like to help you, however I have absolutely no knowledge about CUPS.
I'm maintaining this image that basically just uses the base Debian package and a bunch of drivers.

I'm suggesting you to reach out to people with more knowledge on the topic, cf. https://github.com/olbat/dockerfiles/issues/48#issuecomment-776858057 .

Good luck with your project!

**Comment by Paytah232** [comment]
Hi @olbat,

Thanks for getting back to me. I have created a post on a Synology Forum on Reddit. Hopefully I find some answers there. Here's a link to hopefully help someone in the future:

[https://www.reddit.com/r/synology/comments/p2xqk5/help_with_nodejs_ipp_not_printing_using_cups_in/]

**Comment by olbat** [comment]
Thank you for sharing @Paytah232 . Good luck with your investigation!
