### ISSUE TITLE
install cups at the DiskStation Docker

### ISSUE THREAD

**Issue by loui328** [olbat/dockerfiles#54]
install cups at the DiskStation Docker

PC can use the printer, but user selects a printer and presses "print";
after an elapsed period, an error message is displayed on the iOS device: "The printer is offline."

how to fix it?

**Comment by olbat** [comment]
This repository provides a Docker image that embeds some Debian drivers and the CUPS daemon. I'm not providing support for the CUPS project. Please have a look at [this comment](https://github.com/olbat/dockerfiles/issues/48#issuecomment-776858057) to find the relevant support channel.
