### ISSUE TITLE
Persistent data? Change of username and password? 

### ISSUE THREAD

**Issue by MilorES** [olbat/dockerfiles#64]
I tried several things and in the worst case it didn't start (in some cases it wasn't persistent data or the credentials weren't changed).

**Comment by MilorES** [comment]
I think I was able to find some information. Use "Docker cp" and then bind the volume... to make them persistent, I have to find where CUPS saves the configuration.

Although I still don't know how from the user... I suppose it will also be learning something more about docker :/

Note: I am used to taking images that when you use -v they put the files inside and folders if they are not there (and if they are they keep them)

**Comment by olbat** [comment]
There are hints about how to persist the cupsd configuration file in [the README](https://github.com/olbat/dockerfiles/tree/master/cupsd#run-the-cups-server).

About the username and password, the default configuration checks [the system's user accounts database](https://wiki.debian.org/UserAccounts). You can get more information about the files used to save this database [here](https://www.debian.org/doc/manuals/debian-reference/ch04.en.html) if you want to make them persistent.

A default user _"print"_ is created [in the Dockerfile](https://github.com/olbat/dockerfiles/blob/master/cupsd/Dockerfile#L28), you can create a new one following the same procedure (or change it's password using `passwd`).
