### ISSUE TITLE
HP DeskJet 2300 series print only with colors

### ISSUE THREAD

**Issue by mefisto22** [olbat/dockerfiles#66]
I connected this printer via usb to your cups container. Everything work's fine, but i can't print without colors. I set everywhere to print grayscale, but the printer is printing with colors.

**Comment by olbat** [comment]
This repository has nothing to do with printer drivers packaged in Debian or CUPS. If you need support on that topics, please refer to [this message](https://github.com/olbat/dockerfiles/issues/23#issuecomment-530125636) to find about the relevant support channels.

**Comment by olbat** [comment]
Btw, I created [a new section](https://github.com/olbat/dockerfiles/blob/master/cupsd/README.md#troubleshooting) in the README file with a few pointers. I thought you might be interested. Good luck with debugging your issue!
