### ISSUE TITLE
cupsd  /in unraid6.8.2,docker with HP lap1007.have this err "Waiting for printer to become available"

### ISSUE THREAD

**Issue by wjcroom** [olbat/dockerfiles#67]
in unraid .i hava to add  --privileged="true" ,to let cupsd docker  find the usb printer 
docker run -d -p 631:631  --privileged="true"  -v /var/run/dbus:/var/run/dbus --name cupsd olbat/cupsd
then 
everytime Ｉ print test page ,or send print work. the printer status alway is "Waiting for printer to become available"
how would I to let it print .?

**Comment by wjcroom** [comment]
https://www.linuxquestions.org/questions/slackware-14/waiting-for-printer-to-become-available-4175652261/
i am trying the issue

**Comment by olbat** [comment]
Please have a look at the [troubleshooting section](https://github.com/olbat/dockerfiles/tree/master/cupsd#troubleshooting) of the README file and reach out to the relevant support channels.

**Comment by wjcroom** [comment]
ok I guess this model driver didnt work

**Comment by wjcroom** [comment]
finally ,I　ｇｅｔ 　
HP LaserJet P1007 Foomatic/foo2xqx (recommended) (grayscale, 2-sided printing)
　ｄｒｉｖｅｒ　ｗｏｒｋ　．
ｂｙ　
https://github.com/inveneo/hub-linux-ubuntu/tree/master/install/overlay/usr/share/foo2zjs/firmware
cat /usr/share/foo2zjs/firmware/sihp１００５.dl >/dev/usb/lp0
