### ISSUE TITLE
Daily update of image?

### ISSUE THREAD

**Issue by gvdhoven** [olbat/dockerfiles#68]
I am using watchtower in order to keep my images updated. Can it be that every night a new image is pushed even if nothing has changed?

**Comment by olbat** [comment]
I'm not sure to understand the issue here. Yes the images are being updated daily. What problem do you have? And with which image?

**Comment by gvdhoven** [comment]
Sorry for not being clear; i am referring to the cupsd image. The last change was 19 days ago (readme file) and the dockerfile was even changed 3 months ago; yet on a daily basis my Watchtower docker monitor downloads the new image and restarts the container where this should not be needed if there are no changes, right?

**Comment by olbat** [comment]
The link to the pipeline in the README file is not accurate anymore (I'll remove it). The image is now built from GitLab CI and [everything looks to be going fine](https://gitlab.com/olbat/dockerfiles/-/pipelines). You can also see that the image has been updated recently [on DockerHub](https://hub.docker.com/r/olbat/cupsd).

So yeah, it is indeed updated daily. I don't know Watchtower but it looks like it's just doing the right thing here.
