### ISSUE TITLE
Unable to print on Brother DCP-J125

### ISSUE THREAD

**Issue by DamianPiotrowski** [olbat/dockerfiles#69]
I've managed to install CUPS via Docker without issues.
Printer is connected using USB to the machine
Added binding dev/bus/usb:/dev/bus/usb  so now I can see the printer under CUPS Admin panel.
Added PPD file in Admin Panel. All looks good but it's not printing :( 
I get status: Idle - "File "/usr/lib/cups/filter/brlpdwrapperdcpj125" not available: No such file or directory"

Can you please advise me how I can fix this issue?

**Comment by olbat** [comment]
Sorry, I won't be able to help on that one.

Please, have a look to [this disclaimer](https://github.com/olbat/dockerfiles/tree/master/cupsd#troubleshooting) to get an idea about proper support channels.
