### ISSUE TITLE
Lost printers after Docker image update

### ISSUE THREAD

**Issue by alancyau** [olbat/dockerfiles#70]
It appears after performing a `docker-compose pull` to update the Docker image, the image loses saved printers. Is this normal? Is there a way to prevent printers from disappearing after a Docker image update?

**Comment by olbat** [comment]
Hey @alancyau , I'm going to close this issue, it is not a bug.

The problem you are facing are inherent to how container works/are implemented. I suggest you to have a look at the [Docker volumes documentation](https://docs.docker.com/storage/volumes/) do get a better understanding of this.

Basically what you'd have to do if you want to persist your configuration files is to setup up a volume for the directory where the _cupsd_ settings files are saved. You can look it up online or reach out to one of the support channels mentioned [in the README file](https://github.com/olbat/dockerfiles/tree/master/cupsd#troubleshooting) if you have no idea about where they are saved.
