### ISSUE TITLE
Printer not detected under 'add printer' 

### ISSUE THREAD

**Issue by rbnoorman** [olbat/dockerfiles#74]
Hi, 

Please let me know if this is the wrong place to ask this. 

My Brother HL-1110 is not showing up in the list under 'add printer'. I'm sure it's passed through to the container, it is listed when running lsusb. Is there a way to troubleshoot this? 

I tried manually adding it through usb://Brother/HL-1110?serial=XXXXXXXX but this didn't do the trick either. 

Thanks in advance!

**Comment by olbat** [comment]
If you connected your printer through USB, you'll probably have to turn on USB passthrough. Maybe this can help: https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device .

**Comment by olbat** [comment]
Did it help?

**Comment by olbat** [comment]
No response, closing the issue.
