### ISSUE TITLE
[Cupsd] Suggestion: Drivers for Kyocera printers

### ISSUE THREAD

**Issue by boindil** [olbat/dockerfiles#75]
Hi,

it might be nice to add support for these, I installed the drivers manually like this using the driver from https://www.kyoceradocumentsolutions.de/content/download-center/de/drivers/all/Linux_Universal_Driver_zip.download.zip

```
FROM debian:bullseye as base

FROM olbat/cupsd:latest

COPY --from=base /etc/apt/sources.list.d/ /etc/apt/sources.list.d/

RUN apt-get update

COPY *.deb /install/

RUN apt-get -y install /install/*.deb && rm -rf /install
```

**Comment by olbat** [comment]
Hey @boindil , thank you for the suggestion but this image only contains drivers that are packaged by the Debian team and available in the official deb repositories. I'm sorry but I will not start adding snowflakes drivers for every printer brands, it'll become a living hell to maintain and I'm pretty sure that it won't be okay wrt. the driver's EULA. You can create your own image on the top of this one and distribute it to whoever is interested though!
