### ISSUE TITLE
[Cupsd] Question: How to persist jobs list between container restarts

### ISSUE THREAD

**Issue by boindil** [olbat/dockerfiles#76]
Do you have an idea on how to to this? I did not yet have success finding out.

**Comment by olbat** [comment]
Yes, it's actually documented in the README file: https://github.com/olbat/dockerfiles/tree/master/cupsd#run-the-cups-server 👍

**Comment by boindil** [comment]
Oh wow ... I actually forgot to bind that in portainer and didnt realize that it would have this effect.

Thank you!

**Comment by olbat** [comment]
Npnp 👍
