### ISSUE TITLE
need to re-install and config printer after update docker 

### ISSUE THREAD

**Issue by sofs2005** [olbat/dockerfiles#77]
My printer is brother LDP2550DW, by default CUPS has its own driver but seems cannot use, so I have to install driver downloaded on Brother website and then install with the new driver.
When docker has an update, I have to re-do it, is there any way to remain the drivers an configurations?

**Comment by olbat** [comment]
If you patched the image, you'll have to re-perform your changes every time you update it. If you want to avoid that, don't update your image.

Now if you just patched the image by executing some commands in a running container, you should probably build you custom image instead by [writing a custom Dockerfile](https://docs.docker.com/compose/gettingstarted/) that adds your driver.

I'm going to close the issue has it has nothing to do with this repository. Please refer to the [troubleshooting section](https://github.com/olbat/dockerfiles/tree/master/cupsd#troubleshooting) of the README file to find the relevant support channels for your question.
