### ISSUE TITLE
Trying to run the container on Rapsberry pi, but getting this error: 

### ISSUE THREAD

**Issue by 4rianton** [olbat/dockerfiles#88]
First of all, thanks for working on this dockerfile. 
I am getting this error when I run the command: 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

When I run it directly on the Pi, it works, but not with this docker image. Any pointers will be great!

**Comment by olbat** [comment]
If you are speaking about the cupsd image, it is built only for x86_64 platforms. It seems that your machine has an ARM processor so it wont work. You can learn more about that here: https://docs.docker.com/build/building/multi-platform/ .

I don't have access to the tooling that would be required automate building multi-platform images so I won't be able to help.

Now what you could do is building this image from the Dockerfile manually from your ARM machine.

**Comment by olbat** [comment]
Any news on this @4rianton ?

**Comment by 4rianton** [comment]
Hi @olbat sorry for not being able to respond earlier. I was trying to run it on a raspberry pi so you suspected correctly that I was running it on an ARM platform. I've since switched to just installing cups without docker and seems to be working okay for me atm. 

Thank you for your responsiveness anyway.

**Comment by olbat** [comment]
No problem, glad to see that you sorted out your issue 👍
