### ISSUE TITLE
how can I print from this container?

### ISSUE THREAD

**Issue by emerballen** [olbat/dockerfiles#9]

**Comment by olbat** [comment]
Hi emerballen, I guess you are speaking about the cupsd image ?

If yes, did you try to follow the procedure described in the [README](https://github.com/olbat/dockerfiles/blob/master/cupsd/README.md) ?

**Comment by olbat** [comment]
Can I close the issue @emerballen ?

**Comment by olbat** [comment]
I close the ticket, please feel free to re-open it if necessary.
