### ISSUE TITLE
Add samsung unified driver to CUPS

### ISSUE THREAD

**Issue by Dreaming-Codes** [olbat/dockerfiles#92]
Add https://www.bchemnet.com/suldr/ to CUPS to support older Samsung printers

```bash
bash -c 'echo "deb https://www.bchemnet.com/suldr/ debian extra" >> /etc/apt/sources.list'
apt-get update
apt install suld-driver-1.00.39
```

**Comment by olbat** [comment]
Hey @Dreaming-Codes, thank you for the suggestion but this image only contains drivers that are packaged by the Debian team and available in the official deb repositories. I'm sorry but I will not start adding snowflakes drivers for every printer brands, it'll become a living hell to maintain and I'm pretty sure that it won't be okay wrt. the driver's EULA. You can create your own image on the top of this one and distribute it to whoever is interested though!
