### ISSUE TITLE
HP m1212nf w/ hp-plugin

### ISSUE THREAD

**Issue by rogue-ronin** [olbat/dockerfiles#97]
Running your dockerfile under OpenMediaVault 6, trying to run hp-plugin to get an HP m1212nf to work.

Running hp-plugin gives:

------------------------------------------
| PLUG-IN INSTALLATION FOR HPLIP 3.22.10 |
------------------------------------------

  Option      Description                                       
  ----------  --------------------------------------------------
  d           Download plug-in from HP (recommended)            
  p           Specify a path to the plug-in (advanced)          
  q           Quit hp-plugin (skip installation)                

Enter option (d=download*, p=specify path, q=quit) ? 

-------------------
| DOWNLOAD PLUGIN |
-------------------

Checking for network connection...
error: Network connection not detected.

Not sure how to enable the network connection that it wants.

**Comment by olbat** [comment]
Hey @rogue-ronin , did you try to run your container with network setup to host mode? (as described in the README file)

**Comment by olbat** [comment]
Anyway, you should probably not connect in a container to do that sort of things but rather create a new Dockerfile and use this one as a base.

**Comment by rogue-ronin** [comment]
Apologies for the slow response, I've been ill. :)

I never could get it to work. Turns out that the printer works great if I directly connect it to my router and run all the drivers locally.

I may well have missed the 'host mode' need.

Thank you for creating this, and thank you for responding to me.

Aloha

**Comment by olbat** [comment]
No problem, have a nice day!
